name: Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: src/yarn.lock

      - name: Install dependencies
        run: |
          cd src/
          yarn

      - name: Run tests
        run: |
          cd src/
          yarn test

  publish:
    if: github.event_name == 'release' && github.event.release.target_commitish == 'main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: src/yarn.lock

      - name: Install dependencies
        run: |
          cd src/
          yarn

      - name: Build
        run: |
          cd src/
          yarn build

      - name: Publish to npm
        run: |
          cd src/
          npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"
          npm publish --access public

  updating-docs:
    if: github.event_name == 'release' && github.event.release.target_commitish == 'main'
    needs: [ publish ]
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: src/yarn.lock

      - name: Install dependencies
        run: |
          cd src/
          yarn
          yarn docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4